version: '3'
services:
  banco:
    image: postgres
    ports:
      - "5432:5432"
    container_name: "banco"
    volumes:
      - "./data/banco:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always